# Site-wide settings
# ------------------
#
title: RECOMB-Seq
year: 2026
dates: May 24-25, 2026
iteration: "16th"
location: "Thessaloniki, Greece"
pc_chair1: "Victoria Popic"
pc_chair2: "Kristoffer Sahlin"

#
author:
  name: RECOMB-Seq Conference
  email: recombseq@gmail.com
#
# The `>` after `description:` means to ignore line-breaks until next key. If
#   you wish to omit the line-break after the end of text, use `>-` instead.
# description: >
#   Write an awesome description for your new site here. You can edit this line
#   in _config.yml. It will appear in your document head meta (for Google search
#   results) and in your feed.xml site description.

# Build settings
# --------------
#
# If you wish to use the gem-version of Minima with or without a Gemfile, use
#   the following setting:
# theme: minima
#
# **OR** if you wish to use the theme directly from the GitHub repository by
#   bypassing a Gemfile, use the following setting instead.
#   It is best that you lock to a particular commit and update if uptream changes
#   do not affect your site adversely.
# remote_theme: jekyll/minima@d4d779a
#
# Minima requires the following plugins:
#plugins:
#  - jekyll-feed
#  - jekyll-seo-tag
#
# Uncomment the following setting if you wish to disable deprecation warnings
#   from newer versions of sass converter. Adapt as required.
# sass:
#   quiet_deps: true
#   silence_deprecations: [import]

# Minima-specific settings (applicable to Minima v3 and above only)
# -----------------------------------------------------------------
#
#  *All described config keys below should be nested under the top-level
#   `minima` key.*
#
minima:
  #   Minima skin selection. Available skins are:
  #     * classic            Default, light color scheme.
  #     * dark               Dark variant of the classic skin.
  #     * auto               Adaptive skin based on the classic and dark skins.
  #     * solarized-light    Light variant of solarized color scheme.
  #     * solarized-dark     Dark variant of solarized color scheme.
  #     * solarized          Adaptive skin for solarized color scheme skins.
  skin: auto

#   Social Media Links.
#     Renders icons via Font Awesome Free webfonts CDN, based on ordered list of
#     entries. Valid entry keys:
#       * title    Tooltip rendered on hovering over icon.
#       * icon     Font Awesome icon id. `github` corresponds to `fa-github`.
#       * url      Full URL of social profile.
social_links:
  - title: Email
    icon: envelope
    url: "mailto:recombseq@gmail.com"
  - title: RECOMB-Seq at X
    icon: x-twitter
    url: "https://x.com/RECOMBseq"
  - title: RECOMB-Seq at BlueSky
    icon: bluesky
    url: "https://bsky.app/profile/recombseq.bsky.social"
  - title: RECOMB-Seq at LinkedIn
    icon: linkedin
    url: "https://www.linkedin.com/groups/15794046/"
#
#   Hide syndication feed subscription link.
#     RSS / Atom feed link is always rendered as the last item of social-links
#     list. Set below key to `true` to not have the link to feed rendered as
#     part of social-links list.

hide_site_feed_link: true

main_navigation:
  - title: Home
    url: /index
  - title: Conference
    children:
      - title: Committees
        url: /committees
      - title: Key dates & Deadlines
        url: /keydates_and_deadlines
      - title: Call for Papers
        url: /call_for_papers
      - title: Call for Abstracts
        url: /call_for_abstracts
  - title: Register
    url: /register
    #children:
    #- title: RECOMB and Satellites
    #    url: /register
  - title: Program
    children:
      - title: Program Schedule
        url: /program
      - title: Keynotes
        url: /keynotes
      - title: Poster Guidelines
        url: /posters
  - title: Venue
    children:
      - title: Venue
        url: /venue_satellites
#  - title: Sponsors
#    children:
#      - title: RECOMB Sponsors
#        url: /sponsors
#      - title: Sponsorship Packages
#        url: /sponsorship_packages

# Custom variables
deadlines:
  abstract_submission: "TBA, 23:59 AoE"
  paper_submission: "TBA, 23:59 AoE"
  author_notification: "TBA"
  final_version: "TBA"
  early_registration: "TBA" # placeholder
  late_registration: "TBA" # placeholder
  highlights_submission: "TBA"
  highlights_notification: "TBA"
  highlights_cutoff: "January 1, 2025" # earliest journal pub date for highlights submissions
  poster_and_short_talk_submission: "TBA"
  poster_and_short_talk_notification: "TBA"
  late_poster_and_short_talk_submission: "TBA"
  late_poster_and_short_talk_notification: "TBA"
  conference_dates: "24-25 May 2026"

links:
  easychair: "https://easychair.org/conferences/?conf=recomb2026"
  highlights_chair: "mailto: "
  posters_chair: "mailto: "
  pc_chair1: "mailto:vpopic@broadinstitute.org"
  pc_chair2: "mailto:krsahlin@gmail.com"
#  nav_pages:
#     - about.md
#     - committes.md
#     - register.md
#
#   Set to `true` to show excerpts on the homepage.
#   show_excerpts: false
#
#   Minima date format.
#     The default value is "%b %d, %Y" (e.g. Nov 14, 2023).
#     Refer to https://shopify.github.io/liquid/filters/date/ for valid values
#   date_format: "%b-%d-%Y"
#

